#spring的网关的端口
server:
  port: 10010
#spring的网关的server id
spring:
  application:
    name: ly_gateway
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 # 熔断超时时长：6000ms
ribbon:
  ConnectTimeout: 500 # ribbon链接超时时长
  ReadTimeout: 2000 # ribbon读取超时时长
  MaxAutoRetries: 0  # 当前服务重试次数
  MaxAutoRetriesNextServer: 1 # 切换服务重试次数
  OkToRetryOnAllOperations: false # 是否对所有的请求方式都重试，只对get请求重试
zuul:
  #路由前缀
  prefix: /api
  #将商品微服务映射到/item/** 凡是匹配到item路径的请求,都转到item_service上去
  routes:
    item_service: /item/**
